<?php
/**
 * Shared accessible accordion panel for WooCommerce Edit Order screens.
 *
 * @package BgCommerce3
 */

namespace BgCommerce3\Admin\Order;

use BgCommerce3\Admin\Icons;

defined( 'ABSPATH' ) || exit;

class Panel {

	/**
	 * Open a closed-by-default order panel.
	 *
	 * @param string $id          Unique panel id.
	 * @param string $icon        Core icon name.
	 * @param string $title       Visible title.
	 * @param string $description Optional description.
	 * @param string $status      Optional status text.
	 * @param string $tone        Status tone.
	 * @param string $logo_html    Optional trusted courier logo HTML.
	 * @param string $extra_class  Optional additional CSS classes.
	 * @param bool   $default_open Rule 74/75 — initial state only, from the merchant's global
	 *                             "Отваряй по подразбиране" preference (courier or document
	 *                             section, chosen by the caller). The merchant's own click on
	 *                             the current page always wins after that — this only affects
	 *                             page load.
	 */
	public static function open( $id, $icon, $title, $description = '', $status = '', $tone = 'neutral', $logo_html = '', $extra_class = '', $default_open = false ) {
		$id         = sanitize_html_class( (string) $id );
		$id         = '' !== $id ? $id : 'bgcs-order-panel';
		$content_id = $id . '-content';
		$tone       = self::tone( $tone );
		$classes    = array( 'bgcs-order-panel', 'bgcs-order-panel--tone-' . $tone );

		foreach ( preg_split( '/\s+/', (string) $extra_class ) as $class ) {
			$class = sanitize_html_class( $class );
			if ( '' !== $class ) {
				$classes[] = $class;
			}
		}

		$expanded = (bool) $default_open;
		if ( $expanded ) {
			// Matches the class order.js toggles on click, so the chevron/
			// visual "open" styling (CSS keys off .is-open, not aria-expanded)
			// is correct on first paint too, not just after a manual toggle.
			$classes[] = 'is-open';
		}

		echo '<section id="' . esc_attr( $id ) . '" class="' . esc_attr( implode( ' ', array_unique( $classes ) ) ) . '">';
		echo '<button type="button" class="bgcs-order-panel__trigger" aria-expanded="' . ( $expanded ? 'true' : 'false' ) . '" aria-controls="' . esc_attr( $content_id ) . '" data-bgcs-order-panel-toggle>';
		echo '<span class="bgcs-order-panel__icon' . ( '' !== $logo_html ? ' bgcs-order-panel__icon--logo' : '' ) . '">';
		if ( '' !== $logo_html ) {
			echo $logo_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by Core courier-logo helper.
		} else {
			echo Icons::svg( $icon, 20 ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- fixed local SVG paths.
		}
		echo '</span>';
		echo '<span class="bgcs-order-panel__titles"><span class="bgcs-order-panel__title">' . esc_html( $title ) . '</span>';
		if ( '' !== $description ) {
			echo '<span class="bgcs-order-panel__description">' . esc_html( $description ) . '</span>';
		}
		echo '</span>';
		echo self::status_html( $status, $tone ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- escaped by status_html().
		echo '<span class="bgcs-order-panel__chevron">' . Icons::svg( 'chevron-down', 18 ) . '</span>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- fixed local SVG paths.
		echo '</button>';
		echo '<div id="' . esc_attr( $content_id ) . '" class="bgcs-order-panel__body"' . ( $expanded ? '' : ' hidden' ) . '>';
	}

	/**
	 * Close a panel opened with open().
	 */
	public static function close() {
		echo '</div></section>';
	}

	/**
	 * Render a replaceable status badge.
	 *
	 * @param string $status Status text.
	 * @param string $tone   Status tone.
	 * @return string
	 */
	public static function status_html( $status, $tone = 'neutral' ) {
		$tone = self::tone( $tone );
		$icon = array(
			'neutral' => 'info',
			'success' => 'check',
			'warning' => 'alert',
			'danger'  => 'x-circle',
			'working' => 'rotate',
		);

		if ( '' === (string) $status ) {
			return '<span class="bgcs-order-panel__status bgcs-order-panel__status--' . esc_attr( $tone ) . '" data-bgcs-order-panel-status="' . esc_attr( $tone ) . '" hidden></span>';
		}

		return '<span class="bgcs-order-panel__status bgcs-order-panel__status--' . esc_attr( $tone ) . '" data-bgcs-order-panel-status="' . esc_attr( $tone ) . '">' .
			Icons::svg( $icon[ $tone ], 14 ) .
			'<span>' . esc_html( $status ) . '</span></span>';
	}

	/**
	 * Normalize a supported tone.
	 *
	 * @param string $tone Tone.
	 * @return string
	 */
	private static function tone( $tone ) {
		$tone = sanitize_key( (string) $tone );
		return in_array( $tone, array( 'neutral', 'success', 'warning', 'danger', 'working' ), true ) ? $tone : 'neutral';
	}
}
